name: GitHub Profile Summary Cards

on:
  schedule:
    # Refresh once a day at 00:30 UTC
    - cron: "30 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-summary-cards
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: abhiraj070
          UTC_OFFSET: 5.5
